name: CI

on: [push, pull_request]

jobs:  
  # This matrix job runs the test suite against multiple Ruby versions
  # test_matrix:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby: [3.2, 3.3]
  blah:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone content-schemas
        uses: actions/checkout@v4
        with:
          repository: publishing-platform/publishing-api
          ref: main
          path: tmp/publishing-api 
          token: ${{ secrets.PUBLISHING_PLATFORM_CI_GITHUB_API_TOKEN }}     
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: ${{ matrix.ruby }}
          ruby-version: 3.2
          bundler-cache: true
      - run: bundle exec rake
        env:
          PUBLISHING_PLATFORM_CONTENT_SCHEMAS_PATH: tmp/publishing-api/content_schemas      

  # Branch protection rules cannot directly depend on status checks from matrix jobs.
  # So instead we define `test` as a dummy job which only runs after the preceding `test_matrix` checks have passed.
  # Solution inspired by: https://github.community/t/status-check-for-a-matrix-jobs/127354/3
  test:
    needs: blah
    runs-on: ubuntu-latest
    steps:
      - run: echo "All matrix tests have passed 🚀"

  publish:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/publish-rubygem.yml@main
    secrets:
      GEM_HOST_API_KEY: ${{ secrets.PUBLISHING_PLATFORM_RUBYGEMS_API_KEY }}      